language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: Rf/a9oEL0O4o2OGE5+7QI5AZXwFxKtC1WnKPWNeJ1/zeUKmx6oz/vDO6B8Zv7sp1F2fl5Lyl7gFJu08L0ylUeBMuEzelYSPbgjQzeBxSEDvc+G6IrQ7aoi67gyZWlq3wDs8qS0231UOgUTVAsKoZ7o8bJ4hM9eAIfN6bonikiz/bfpL4lWP7yzBL+NRim4064DmDjWwFpqARFhwTzxD/2249JsdhXiwsrW7w2VhU18o+1B2YJrjg8MSIVycRIUjt0QEzJIZzRmPJqAeyjFztyqzza5xunyZiqzTHghTQFX35/15n2zaDRAUbhmqc17hAvva16T7CdFO61pOxUjAyLPDtkyBCTfN7U1ACa5bCn7pAyHfZ+e0BE1hmH6/rVZVs6JQR/ZkLz+ywptJmBdnfxvHDAgWCG6cb2uyhiM4quETv2onEvmsGEfFcYQWBYrHYEMxA5XbBmK96AQZSPFgdq2fMAOAk57K80G55sUIIXOcblalK23kxLNVu9rh+ux0yzCCaXpZc7Nn6Eb4D1A2OBebHpzovSMkgVHBdJ/eZB4k8N2imZ0XXkDxjTCL3x82Ne/3cGqHUaao8cFMGLjdfjDXBNjvdsl3RGkYGegg4Aeo1SEUC0us42p/oFHWpbOt1MxS6Haba126bnV4GWRbp98eZWXqDmmvcqrqWTRvC5Ws=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: ZRHct6q67Q/IQVA/tzcWU4sSC/uYLinzARjz0uxNJbOFHaigHXqqMYcySe1yUAVIeHflp+6yuZSTIo/PxzdT/kzX1goFbMoSXD6BVO6ViAnrjJdPrHzDMEDdEQGnMdKrIT1U74xbtsCF6+xcciHYUxL83LdM3u1O/np+af8ULOj5XaQgRBysFTuHkmCeLvUlvrPcxaA3qvSx9lmzBimwrMhG1yLKxZHLilgo6gtjTfFSKuVW1QOkPC9uBIJrXhV27x3BZm30HFpq6U8I1KCDYy1PgbwHSr/SDhlF6qlud3qIwCzBSWpzvzXnJJ5iPkEsEav6CLdKlfoShp2mfesscVdJdzVpj8aJ5Pug8a0ySUaLsAgAng2lXHoEtcsoBdxLPPu9p4Nog+c8vFY5TV6x3SGqBqYxh94gKnkBatJ8cyYi1mN6+W3gmBqAWFCVOdPZWjWaCsN2gOsD20dZqYJugoJBn6dQraubI0NDT0akYUR0Mpams3Nm27ha5LXfnZvqikGjnEYyYBmdhFy+5y4M2g3CMTVgGh3OpUSFHczDSJLhKYF6TnekUNjxba0P0fGu94/Bj5zwcklbWyvcz4PE8evPQmpQCgXqnJfXEVuGu6/+guqojkRIQ15/KymJkych0ckOsZLrAymvVDKsaSyBra8JpYwjhn19agyn1BxcoQs=
sudo: false
